version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: oda_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    container_name: oda_redis
    restart: always
    ports:
      - "6379:6379"

  hop:
    image: apache/hop:2.18.0
    container_name: oda_hop_prod
    profiles: ["prod"] # Este container só subirá se você explicitamente pedir (--profile prod)
    environment:
      HOP_PROJECT_NAME: ${HOP_PROJECT_NAME:-oda}
      HOP_PROJECT_FOLDER: ${HOP_PROJECT_FOLDER:-/files/apps/data_pipeline/hop}
      OPEN_ALEX_KEY: ${OPEN_ALEX_KEY}
    volumes:
      - .:/files
    depends_on:
      - postgres
      
volumes:
  postgres_data:
